# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test SECP256K1
      run: dotnet run --project /home/runner/work/Wheel/Wheel/Tests/Test_SECP256K1
    - name: Test SECP160R1
      run: dotnet run --project /home/runner/work/Wheel/Wheel/Tests/Test_SECP160R1
    - name: Test SECP192R1
      run: dotnet run --project /home/runner/work/Wheel/Wheel/Tests/Test_SECP192R1
    - name: Test SECP224R1
      run: dotnet run --project /home/runner/work/Wheel/Wheel/Tests/Test_SECP224R1
    - name: Test SECP256R1
      run: dotnet run --project /home/runner/work/Wheel/Wheel/Tests/Test_SECP256R1
    - name: Test SECP384R1
      run: dotnet run --project /home/runner/work/Wheel/Wheel/Tests/Test_SECP384R1
    - name: Test SECP521R1
      run: dotnet run --project /home/runner/work/Wheel/Wheel/Tests/Test_SECP521R1
    - name: Test ECDH
      run: dotnet run --project /home/runner/work/Wheel/Wheel/Tests/Test_ECDH
    - name: Test EdDH
      run: dotnet run --project /home/runner/work/Wheel/Wheel/Tests/Test_EdDH
    - name: Test EdDSA
      run: dotnet run --project /home/runner/work/Wheel/Wheel/Tests/Test_EdDSA
    - name: Test EdDSA_Seed
      run: dotnet run --project /home/runner/work/Wheel/Wheel/Tests/Test_EdDSA_Seed
#    - name: Test PBKDF2
#      run: dotnet run --project /home/runner/work/Wheel/Wheel/Tests/Test_PBKDF2
    - name: Test Hashing
      run: dotnet run --project /home/runner/work/Wheel/Wheel/Tests/Test_Hashing
    - name: Test HMAC
      run: dotnet run --project /home/runner/work/Wheel/Wheel/Tests/Test_HMAC
    - name: Test Shamir
      run: dotnet run --project /home/runner/work/Wheel/Wheel/Tests/Test_Shamir
    - name: Test Base58
      run: dotnet run --project /home/runner/work/Wheel/Wheel/Tests/Test_Base58
    - name: Test Bech32
      run: dotnet run --project /home/runner/work/Wheel/Wheel/Tests/Test_Bech32
    - name: Test AES
      run: dotnet run --project /home/runner/work/Wheel/Wheel/Tests/Test_AES
